# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'benhvien-app-simple' do
  use_frameworks!

    pod 'PureLayout'
    pod 'IQKeyboardManager'
    pod 'IQDropDownTextField'
    pod 'KASlideShow'

end
